export const allServices = {
  washingMachine: [
    "Washing Machine Installation",
    "Washing Machine Uninstallation",
    "Washing Machine Repair and Services",
    "Washing Machine Drum Cleaning",
    "Washing Machine Noise Issue Repair",
    "Washing Machine Power Issue Repair",
    "Washing Machine Water Drainage Issue",
    "Washing Machine Door Seal Replacement",
  ],
  refrigerator: [
    "Refrigerator Installation",
    "Refrigerator Uninstallation",
    "Refrigerator Repair and Services",
    "Refrigerator Gas Refill",
    "Refrigerator Cooling Issue Repair",
    "Refrigerator Thermostat Replacement",
    "Refrigerator Door Seal Replacement",
    "Refrigerator Compressor Replacement",
  ],
  waterPurifier: [
    "Water Purifier Installation",
    "Water Purifier Uninstallation",
    "Water Purifier Repair and Services",
    "Water Purifier Filter Replacement",
    "RO Membrane Replacement",
    "Water Flow Issue Repair",
    "UV Lamp Replacement",
    "Water Leakage Repair",
  ],
  ac: [
    "AC Installation (Split/Window)",
    "AC Uninstallation",
    "AC Repair & Services",
    "AC Gas Refill",
    "AC General Cleaning",
    "AC Deep Cleaning (Jet/Steam)",
    "AC Cooling Issue Repair",
    "AC Fan Motor Replacement",
    "AC PCB Repair or Replacement",
    "AC Water Leakage Repair",
    "AC Noise Issue Repair",
  ],
  microwave: [
    "Microwave Repair and Services",
    "Microwave Not Heating Issue Repair",
    "Microwave Door Lock Repair",
    "Microwave Turntable Issue Repair",
    "Microwave Power Issue Repair",
    "Microwave Installation (Built-in Units)",
  ],
  dishwasher: [
    "Dishwasher Installation",
    "Dishwasher Uninstallation",
    "Dishwasher Repair and Services",
    "Dishwasher Not Draining Issue Repair",
    "Dishwasher Not Cleaning Properly",
    "Dishwasher Noise Issue Repair",
    "Dishwasher Door Issue Repair",
    "Dishwasher Filter Cleaning",
  ],
};
